name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: CI Success
        run: echo "CI completed successfully"