name: Auto Issue Resolver

on:
  schedule:
    # 全ての時間帯で1時間ごとに実行
    - cron: '0 * * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  process-issue:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Select and add processing label to random issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const allIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });

            if (allIssues.data.length === 0) {
              console.log('No open issues found');
              return;
            }

            // processing ラベルが付いていないissueをフィルタリング
            const availableIssues = allIssues.data.filter(issue =>
              !issue.labels.some(label => label.name === 'processing')
            );

            if (availableIssues.length === 0) {
              console.log('No issues available for processing (all already have processing label)');
              return;
            }

            // ランダムに一つ選択
            const randomIndex = Math.floor(Math.random() * availableIssues.length);
            const selectedIssue = availableIssues[randomIndex];

            // processing ラベルを追加
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: selectedIssue.number,
              labels: ['processing']
            });

            console.log(`Added processing label to issue #${selectedIssue.number}: ${selectedIssue.title}`);
            